### PR TITLE
Shellcheck and some zsh support

### PR DESCRIPTION
**Pull request by qfjp**
Fixed all shellcheck warnings, and made some functions to assist in choosing which prompt will be replaced with the current project name. Right now it currently supports PS1 by default, or RPROMPT if you're using zsh

### CODE REVIEW

**Comment by eivind88** [comment]
This breaks prompt-integration for me on `bash` 3.2.57(1), and doesn't change the prompt on `zsh` 5.0.5.
Both of these are OS X 10.10 default.

**Comment by EivindArvesen** [comment]
This breaks prompt-integration for me on `bash` 3.2.57(1), and gives a bunch of errors:

``` bash
Eivind@Eivinds-Air.lan: ~/Desktop/prm > source prm.sh start test
-bash: [e[0: command not found
-bash: 36m]Eivind[e[1: command not found
-bash: 30m]@[e[0: command not found
-bash: 31m]Eivinds-Air.lan[e[1: command not found
-bash: 30m]:: command not found
-bash: 32m]w: command not found
Starting project test
Eivind@Eivinds-Air.lan: ~/Desktop/prm >
```

``` bash
source prm.sh stop
Stopping project test
-bash: 36m]Eivind[e[1: command not found
-bash: 30m]@[e[0: command not found
-bash: 31m]Eivinds-Air.lan[e[1: command not found
-bash: 30m]:: command not found
-bash: 32m]w: command not found
[e[0
```

As you can see from the last line, stopping a projects breaks my prompt.

On `zsh` 5.0.5 I see no change in the prompt, and I'm getting this error:

``` zsh
Eivinds-Air%source prm.sh start test
(eval):fg:1: job not found: m%#
Starting project test
Eivinds-Air%
```

Both of these are OS X 10.10 default versions.

**Comment by qfjp** [comment]
Looks like I got the quoting around the indirect expansion wrong, so it was trying to execute your prompt. At least bash should work now. I don't know why zsh isn't working for you, but I'm using zsh and the right prompt is updating just fine. I'll try it on a friend's macbook later tonight to see if it has to do with whatever zsh mac has installed. <del>Are you using the default zsh version that's installed or are you using the most recent version (from source or brew or whatever)?</del>

Edit: Nevermind, you already said default. I'll see if my changes still work on Yosemite

**Comment by qfjp** [comment]
A quick demo of what I'm seeing in zsh:
https://asciinema.org/a/6gtnwze2h2bomtbok2hcuohrt

**Comment by EivindArvesen** [comment]
I pulled your latest commit, and things now seem to work just fine in both `bash` and in `zsh`.
Merging as soon as I resolve conflicts.

**Comment by EivindArvesen** [comment]
I was in the process of  fixing the the conflicts before you did it yourself, 
so I have adressed some issues I noticed upon inspection:
- 81f48ff0a951863325788b95d7c4b1e20401f7f5: Revert 239510c05a4d9ad962de7560ee74dda4e0abb673; these don't need to be in the source.
- df016ed9a01e6a8cb27a27428316096f4b2e41d5: Revert adbf77c2de6c3a396daec39a58a57ef76346e276; there must be no "exit" in the source, as this will kill the shell (since prm is sourced); Addictionally, there are plans to use return codes upon errors, and use specific terminology in the few error messages that are needed.
- 0d7897240e275cecaec4057a7f73f03f05611df2: Cherry-pick f1d22533abd57f89ae0849f47983517e07920e1b; These changes were seemingly undone.

**Pull request merged**
