### PR TITLE
zsh completion

### PR DESCRIPTION
**Pull request by lelongg**
First shot at zsh completion

### CODE REVIEW

**Comment by EivindArvesen** [comment]
Sorry; I haven't had an opportunity to review this before now.

Before I accept the PR:
The changes in `prm.sh` are just about avoiding Bash-isms, right?

**Comment by EivindArvesen** [comment]
@lelongg: Ping

**Comment by lelongg** [comment]
Yes it is ! (sorry for the late answer)

**Comment by EivindArvesen** [comment]
Great!
No problem, I was initially pretty tardy myself ;)

**Pull request merged**
